#!/usr/bin/env python3
"""
Fast batch validation of NIMROD dumpgll files versus an IMAS mhd_linear IDS.

Unlike the thin batch wrapper, this script does NOT start a new Python process for
one field/mode/part comparison.  It imports the comparison module once, opens each
mhd_linear occurrence once, reads/stitches each dump once, and then computes all
requested metrics in-process.

It is intended to be consistent with compare_mhd_linear_validation.py
and therefore with the current dump2imas logic for pressure and mass density.
"""

from __future__ import annotations

import argparse
import csv
import importlib.util
import math
import sys
from pathlib import Path
from types import SimpleNamespace
from typing import Any, Iterable

import numpy as np


def csv_list(value: str | None, cast=str) -> list:
    if value is None:
        return []
    out = []
    for item in str(value).split(','):
        item = item.strip()
        if not item:
            continue
        out.append(cast(item))
    return out


def to_float(value: object) -> float:
    try:
        return float(value)  # type: ignore[arg-type]
    except Exception:
        return float('nan')


def fmt_sci(value: object, sig: int = 3) -> str:
    x = to_float(value)
    if math.isnan(x):
        return '--'
    if x == 0.0:
        return '0'
    return f'{x:.{sig}e}'


def fmt_corr(value: object) -> str:
    x = to_float(value)
    if math.isnan(x):
        return '--'
    return f'{x:.16f}'


def field_label(row: dict[str, str]) -> str:
    q = row.get('quantity', '')
    comp = row.get('component', '')
    part = row.get('part', '')
    name_map = {'n': r'\rho', 't': r'T', 'p': r'p', 'b': r'B', 'v': r'V'}
    base = name_map.get(q, q)
    if comp and comp not in ('None', 'none'):
        base += f'_{comp}'
    if part:
        base += f' ({part})'
    return base


def summarize(rows: list[dict[str, str]]) -> list[dict[str, str]]:
    groups: dict[tuple[str, str, str, str], list[dict[str, str]]] = {}
    for row in rows:
        key = (row.get('occ', ''), row.get('quantity', ''), row.get('component', ''), row.get('part', ''))
        groups.setdefault(key, []).append(row)

    summary_rows: list[dict[str, str]] = []
    for _key, group in sorted(groups.items()):
        l2 = [to_float(r.get('l2_rel')) for r in group]
        rmse = [to_float(r.get('rmse')) for r in group]
        max_abs = [to_float(r.get('max_abs')) for r in group]
        corr = [to_float(r.get('corr')) for r in group]
        npts = [to_float(r.get('n_points')) for r in group]
        row0 = group[0]
        finite_npts = [x for x in npts if not math.isnan(x)]
        finite_l2 = [x for x in l2 if not math.isnan(x)]
        finite_rmse = [x for x in rmse if not math.isnan(x)]
        finite_max_abs = [x for x in max_abs if not math.isnan(x)]
        finite_corr = [x for x in corr if not math.isnan(x)]
        summary_rows.append({
            'occ': row0.get('occ', ''),
            'field': field_label(row0),
            'n_comparisons': str(len(group)),
            'n_points_min': str(int(min(finite_npts))) if finite_npts else '',
            'l2_rel_max': fmt_sci(max(finite_l2)) if finite_l2 else '--',
            'rmse_max': fmt_sci(max(finite_rmse)) if finite_rmse else '--',
            'max_abs_max': fmt_sci(max(finite_max_abs)) if finite_max_abs else '--',
            'corr_min': fmt_corr(min(finite_corr)) if finite_corr else '--',
        })
    return summary_rows


def write_latex_summary(rows: list[dict[str, str]], path: Path, caption: str, label: str) -> None:
    summary = summarize(rows)
    with path.open('w', encoding='utf-8') as f:
        f.write('% Auto-generated by run_mhd_linear_validation_batch_fast.py\n')
        f.write('\\begin{table}[t]\n')
        f.write('\\centering\n')
        f.write('\\caption{' + caption + '}\n')
        f.write('\\label{' + label + '}\n')
        f.write('\\begin{tabular}{llrrrr}\n')
        f.write('\\hline\n')
        f.write('Occurrence & Field & $N_{\\mathrm{cmp}}$ & $N_{\\mathrm{pts,min}}$ & $\\max \\epsilon_{L2}$ & $\\min r$ \\\\\n')
        f.write('\\hline\n')
        for row in summary:
            f.write(
                f"{row['occ']} & {row['field']} & {row['n_comparisons']} & {row['n_points_min']} & "
                f"{row['l2_rel_max']} & {row['corr_min']} \\\\\n"
            )
        f.write('\\hline\n')
        f.write('\\end{tabular}\n')
        f.write('\\end{table}\n')


def load_compare_module(script_path: Path) -> Any:
    spec = importlib.util.spec_from_file_location('mhd_linear_compare_mod', str(script_path))
    if spec is None or spec.loader is None:
        raise RuntimeError(f'cannot load comparison script: {script_path}')
    mod = importlib.util.module_from_spec(spec)
    sys.modules['mhd_linear_compare_mod'] = mod
    spec.loader.exec_module(mod)
    return mod


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        description='Fast batch validation of native NIMROD dumpgll files against IMAS mhd_linear.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument('dumpgll', nargs='+', help='dumpgll HDF5 files to validate')
    p.add_argument('--script', default='compare_mhd_linear_validation.py',
                   help='comparison module to import for converter-consistent functions')

    p.add_argument('--entry', default=None,
                   help='IMAS HDF5 entry directory, e.g. d3d/4/163518/5. If omitted, use --dbpath --dd --pulse --run.')
    p.add_argument('--backend', default='hdf5')
    p.add_argument('--dbpath', default='.', help='base IMAS database path used when --entry is omitted')
    p.add_argument('--dd', default=None, help='IMAS database name / tokamak, e.g. d3d')
    p.add_argument('--dd-version', default='4.1.1')
    p.add_argument('--dd-version-dir', default=None,
                   help='optional IMAS major-version directory override, e.g. 4')
    p.add_argument('--pulse', default=None, help='IMAS pulse / shot number used when --entry is omitted')
    p.add_argument('--run', default=None, help='IMAS run number used when --entry is omitted')

    p.add_argument('--occ', default='1', help='comma-separated IMAS mhd_linear occurrences')
    p.add_argument('--occ-base', default='1', help='base occurrence convention')
    p.add_argument('--quantities', default='t,p,b,v', help='comma-separated subset of n,t,p,b,v')
    p.add_argument('--components', default='r,z,phi', help='components for vector quantities b and v')
    p.add_argument('--parts', default='real,imag', help='comma-separated real,imag,amp')
    p.add_argument('--pressure-source', default='auto',
                   choices=['auto', 'dump2imas', 'explicit', 'total', 'total_minus_electron', 'reconstruct', 'thermal_only', 'density_only'],
                   help='native pressure reference')
    p.add_argument('--species-role', default='auto', choices=['auto', 'electron', 'ion'],
                   help='species role. auto follows the comparison script logic')
    p.add_argument('--native-species-index', default=None,
                   help='diagnostic override for native species index')
    p.add_argument('--ion-mass-amu', default='2.0',
                   help='ion mass used for mass_density_perturbed; default matches dump2imas')
    p.add_argument('--nimrod-in', default=None,
                   help='optional nimrod.in path')
    p.add_argument('--no-nimrod-in-auto', action='store_true',
                   help='disable automatic nimrod.in discovery')
    p.add_argument('--dens-pert-order', default='species_major', choices=['species_major', 'mode_major'])
    p.add_argument('--electrons-index', type=int, default=0)
    p.add_argument('--n-tor', required=True, help='comma-separated toroidal mode numbers to validate')
    p.add_argument('--ids-time-tolerance', default=None, type=float)
    p.add_argument('--no-match-dump-time', action='store_true',
                   help='do not match IDS time to dump time; use --ids-time-index')
    p.add_argument('--ids-time-index', default=0, type=int)
    p.add_argument('--raw-ids-time-index', action='store_true')
    p.add_argument('--skip-failures', action='store_true', help='record failures and continue')
    p.add_argument('--out-csv', default='validation_mhd_linear_full.csv')
    p.add_argument('--out-tex', default='validation_mhd_linear_summary.tex')
    p.add_argument('--caption', default='Summary of mhd_linear validation metrics comparing deposited IMAS fields with native NIMROD dump fields.')
    p.add_argument('--label', default='tab:mhd-linear-validation-summary')
    p.add_argument('--progress-every', type=int, default=20, help='print progress every N successful comparisons')
    return p


def make_dump_args(args: argparse.Namespace, dump_path: Path, mod: Any) -> tuple[SimpleNamespace, str | None]:
    dump_args = SimpleNamespace(
        time=None,
        dens_pert_order=args.dens_pert_order,
        ion_mass_amu=float(args.ion_mass_amu),
    )
    nimrod_in_path = args.nimrod_in
    if nimrod_in_path is None and not args.no_nimrod_in_auto:
        for c in (Path('nimrod.in'), dump_path.resolve().parent / 'nimrod.in'):
            if c.is_file():
                nimrod_in_path = str(c)
                break
    if nimrod_in_path:
        setattr(dump_args, '_series_nimrod_in_path', str(nimrod_in_path))
        nimrod_species_info = getattr(mod, '_nimrod_species_info', None)
        if nimrod_species_info is not None:
            try:
                setattr(dump_args, '_nimrod_species', nimrod_species_info(str(nimrod_in_path)))
            except Exception:
                pass
    return dump_args, nimrod_in_path


def dump_mode_index(data: dict[str, Any], n_tor: int, mode_index: int | None = None) -> int:
    nm = int(data.get('nmodes', 0) or 0)
    if nm <= 0:
        raise RuntimeError('native dump does not appear to contain perturbation modes')
    if mode_index is not None:
        i = int(mode_index)
    else:
        keff = np.ravel(np.asarray(data.get('keff', []), dtype=float))
        matches = np.where(np.rint(keff).astype(int) == int(n_tor))[0]
        if matches.size == 0:
            raise RuntimeError(f'n_tor={n_tor} not found in dump keff={keff.tolist()}')
        i = int(matches[0])
    if i < 0 or i >= nm:
        raise RuntimeError(f'dump mode index {i} out of range 0..{nm - 1}')
    return i


def main() -> int:
    args = build_parser().parse_args()
    script = Path(args.script)
    if not script.exists():
        candidate = Path(__file__).resolve().parent / args.script
        if candidate.exists():
            script = candidate
        else:
            raise SystemExit(f'comparison script not found: {args.script}')

    if args.entry is None:
        missing = [name for name in ('dd', 'pulse', 'run') if getattr(args, name) in (None, '')]
        if missing:
            raise SystemExit('provide either --entry, or --dbpath --dd --pulse --run (missing: ' + ', '.join(missing) + ')')

    mod = load_compare_module(script)

    # Resolve entry with the exact helper used by the comparison script.
    entry_ns = SimpleNamespace(
        entry=args.entry,
        dbpath=args.dbpath,
        dd=args.dd,
        dd_version=args.dd_version,
        dd_version_dir=args.dd_version_dir,
        pulse=args.pulse,
        run=args.run,
    )
    entry = mod.resolve_validator_entry_path(entry_ns)

    quantities = csv_list(args.quantities, str)
    components = csv_list(args.components, str)
    parts = csv_list(args.parts, str)
    modes = csv_list(args.n_tor, int)
    occs = csv_list(args.occ, int)
    occ_base = int(args.occ_base)

    # Open the database once and read each requested occurrence once.
    db, _uri, imas_mod = mod.open_dbentry(args.backend, str(entry), mode='r', dd_version=args.dd_version)
    try:
        factory = mod.ids_factory(imas_mod, args.dd_version or '')
        mhd_by_occ: dict[int, Any] = {}
        for occ in occs:
            mhd_by_occ[occ] = mod.get_ids(db, factory, 'mhd_linear', int(occ))

        rows: list[dict[str, str]] = []
        failures: list[dict[str, str]] = []
        n_ok = 0

        for dump_name in args.dumpgll:
            dump_path = Path(dump_name)
            dump_args, nimrod_in_path = make_dump_args(args, dump_path, mod)
            data = mod.read_and_stitch_dump(dump_path, dump_args)

            for occ in occs:
                ids_species_index = int(occ) - occ_base
                if ids_species_index < 0:
                    raise RuntimeError(f'occ={occ} is smaller than occ-base={occ_base}')

                if args.species_role == 'auto':
                    species_role = 'electron' if ids_species_index == int(args.electrons_index) else 'ion'
                else:
                    species_role = args.species_role
                converter_species_index = ids_species_index
                compare_species_index = int(args.native_species_index) if args.native_species_index is not None else converter_species_index
                effective_electrons_index = int(args.electrons_index) if species_role == 'electron' else -999999
                mhd = mhd_by_occ[int(occ)]

                ids_time_value = None
                if not args.no_match_dump_time:
                    ids_time_value = float(data.get('time', np.nan))
                    if not np.isfinite(ids_time_value):
                        raise RuntimeError('--match-dump-time requested, but the dump time is not finite')

                for quantity in quantities:
                    comps: Iterable[str | None] = components if quantity in ('b', 'v') else [None]
                    for component in comps:
                        for part in parts:
                            for mode in modes:
                                try:
                                    dmode = dump_mode_index(data, int(mode))
                                    R_dump, Z_dump, F_dump = mod.extract_dump_field(
                                        data,
                                        quantity=quantity,
                                        species_index=compare_species_index,
                                        mode_index=dmode,
                                        part=part,
                                        component=component,
                                        ion_mass_amu=float(args.ion_mass_amu),
                                        electrons_index=effective_electrons_index,
                                        pressure_source=args.pressure_source,
                                    )
                                    R_ids, Z_ids, F_ids, ti_raw, mi, ids_time = mod.extract_ids_field(
                                        mhd,
                                        ids_time_index=int(args.ids_time_index),
                                        raw_ids_time_index=bool(args.raw_ids_time_index),
                                        ids_time_value=ids_time_value,
                                        ids_time_tolerance=args.ids_time_tolerance,
                                        n_tor=int(mode),
                                        mode_index=None,
                                        quantity=quantity,
                                        part=part,
                                        component=component,
                                    )
                                    R_dump, Z_dump, F_dump, R_ids, F_ids = mod.align_fields(
                                        R_dump, Z_dump, F_dump, R_ids, Z_ids, F_ids
                                    )
                                    metrics = mod.compute_metrics(F_dump, F_ids)

                                    dump_time = float(data.get('time', np.nan))
                                    dt = abs(float(ids_time) - dump_time)
                                    row: dict[str, str] = {
                                        'dumpgll': str(dump_name),
                                        'dump_time': f'{dump_time:.12g}',
                                        'ids_time': f'{float(ids_time):.12g}',
                                        'abs_time_difference': f'{dt:.16e}' if np.isfinite(dt) else '',
                                        'occ': str(occ),
                                        'ids_species_index': str(ids_species_index),
                                        'species_role': species_role,
                                        'compare_species_index': str(compare_species_index),
                                        'converter_species_index': str(converter_species_index),
                                        'native_species_index': str(compare_species_index),
                                        'quantity': quantity,
                                        'component': '' if component is None else str(component),
                                        'part': part,
                                        'n_tor_requested': str(mode),
                                        'ids_time_slice_raw_index': str(ti_raw),
                                        'ids_mode_index': str(mi),
                                        'dump_mode_index': str(dmode),
                                        'dump_shape': str(F_dump.shape),
                                        'ids_shape': str(F_ids.shape),
                                        'dump_min': f'{float(np.nanmin(F_dump)):.16e}',
                                        'dump_max': f'{float(np.nanmax(F_dump)):.16e}',
                                        'ids_min': f'{float(np.nanmin(F_ids)):.16e}',
                                        'ids_max': f'{float(np.nanmax(F_ids)):.16e}',
                                        'dump_l2': f'{float(np.linalg.norm(np.asarray(F_dump, dtype=float))):.16e}',
                                        'ids_l2': f'{float(np.linalg.norm(np.asarray(F_ids, dtype=float))):.16e}',
                                        'dump_sha16': mod.array_signature(F_dump),
                                        'ids_sha16': mod.array_signature(F_ids),
                                        'entry': str(entry),
                                        'backend': str(args.backend),
                                        'dd_version': str(args.dd_version),
                                        'nimrod_in': nimrod_in_path if nimrod_in_path else 'None',
                                        'pressure_source': args.pressure_source if quantity == 'p' else '',
                                    }
                                    for k, v in metrics.items():
                                        if isinstance(v, float):
                                            row[k] = f'{v:.16e}'
                                        else:
                                            row[k] = str(v)
                                    row['array_signature_equal'] = str(row.get('dump_sha16') == row.get('ids_sha16'))
                                    rows.append(row)
                                    n_ok += 1
                                    if args.progress_every > 0 and (n_ok % args.progress_every == 0):
                                        print(f'[OK] {n_ok} comparisons complete; current dump={dump_path.name} occ={occ} q={quantity} comp={component} part={part} n={mode}', flush=True)
                                except Exception as exc:
                                    failure = {
                                        'dumpgll': str(dump_name),
                                        'occ': str(occ),
                                        'quantity': quantity,
                                        'component': '' if component is None else str(component),
                                        'part': part,
                                        'n_tor': str(mode),
                                        'error': repr(exc),
                                    }
                                    failures.append(failure)
                                    if args.skip_failures:
                                        print(f'[WARN] failed: dump={dump_path.name} occ={occ} q={quantity} comp={component} part={part} n={mode}: {exc}', file=sys.stderr)
                                        continue
                                    raise

    finally:
        try:
            db.close()
        except Exception:
            pass

    if not rows:
        raise SystemExit('no successful validation rows were produced')

    preferred = [
        'dumpgll', 'dump_time', 'ids_time', 'abs_time_difference',
        'occ', 'ids_species_index', 'species_role', 'compare_species_index', 'converter_species_index',
        'quantity', 'component', 'part', 'n_tor_requested',
        'ids_time_slice_raw_index', 'ids_mode_index', 'dump_mode_index',
        'dump_shape', 'ids_shape', 'n_points', 'l2_rel', 'rmse', 'nrmse_rms',
        'max_abs', 'max_rel_peak', 'mean_abs', 'bias', 'corr',
        'dump_min', 'dump_max', 'ids_min', 'ids_max', 'dump_l2', 'ids_l2',
        'dump_sha16', 'ids_sha16', 'array_signature_equal',
        'entry', 'backend', 'dd_version', 'nimrod_in', 'pressure_source',
    ]
    all_keys: list[str] = []
    for key in preferred:
        if any(key in r for r in rows):
            all_keys.append(key)
    for row in rows:
        for key in row:
            if key not in all_keys:
                all_keys.append(key)

    out_csv = Path(args.out_csv)
    with out_csv.open('w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=all_keys)
        writer.writeheader()
        writer.writerows(rows)

    out_tex = Path(args.out_tex)
    write_latex_summary(rows, out_tex, caption=args.caption, label=args.label)

    if failures:
        fail_csv = out_csv.with_name(out_csv.stem + '_failures.csv')
        with fail_csv.open('w', newline='', encoding='utf-8') as f:
            keys = sorted({k for row in failures for k in row})
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(failures)
        print(f'[WARN] wrote failures: {fail_csv}', file=sys.stderr)

    print(f'wrote CSV: {out_csv}')
    print(f'wrote LaTeX summary: {out_tex}')
    print(f'successful comparisons: {len(rows)}')
    if failures:
        print(f'failed comparisons: {len(failures)}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
