# Convenience Makefile for reviewers who enter the tests directory.
# All real targets are defined in the package-level Makefile.

.PHONY: help install check test validate clean-test

help install check test validate clean-test:
	$(MAKE) -C .. $@
